name: Snowflake CI/CD

on:
  push:
    branches:
      - main  # Only trigger for main branch

jobs:
  snowflake-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install snowflake-connector-python

      - name: Deploy to Snowflake (Main Branch Only)
        run: |
          snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                  -u ${{ secrets.SNOWFLAKE_USER }} \
                  -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                  -r ${{ secrets.SNOWFLAKE_ROLE }} \
                  -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
                  -d ${{ secrets.SNOWFLAKE_DATABASE }} \
                  
